---
abstract: 'HTML Form Creation, Rendering and Validation Framework'
author:
  - 'Carl Franks'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::NoWarnings: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-FormFu
no_index:
  directory:
    - examples
    - share
    - share
    - inc
    - t
    - examples
requires:
  Class::Accessor::Chained::Fast: 0
  Class::C3: 0
  Config::Any: 0.10
  Crypt::CBC: 0
  Crypt::DES: 0
  Data::Visitor::Callback: 0
  Date::Calc: 0
  DateTime: 0.38
  DateTime::Format::Builder: 0.7901
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 0
  DateTime::Locale: 0
  Email::Valid: 0
  File::ShareDir: 0
  HTML::Scrubber: 0
  HTML::TokeParser::Simple: 3.14
  HTTP::Headers: 1.64
  List::MoreUtils: 0
  Locale::Maketext::Simple: 0
  Module::Pluggable: 0
  Regexp::Common: 0
  Regexp::Copy: 0
  Task::Weaken: 0
  Template: 0
  YAML::Syck: 1.05
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.03002
