---
legend: Jimi
elements:
 - type: text
   name: age
   comment: x
   label: Age
   constraints:
   - type: Integer
     message: No integer.
   - type: Integer
     message: This too!
 - type: text
   name: name
   label: Name
 - type: hidden
   name: ok
   value: OK 
